### ISSUE TITLE
1.16.x (just released) - test failure

### ISSUE THREAD

**Issue by Temikus** [google/ts-bridge#110]
So 1.16 _just_ released and it seems that something has changed to make a couple of tests fail only for `1.16.x` build, notably:
- TestUpdateAllMetrics
- TestUpdateAllMetricsErrors

See: https://github.com/google/ts-bridge/runs/1933024386

Assigning to Adi to take a look later (this is not very urgent). Sorry for not doing it myself, but 1.16 just released and this didn't fail in RC so I couldn't have known.

**Comment by nerdinary** [comment]
fixed in fixed in https://github.com/google/ts-bridge/pull/182
