### ISSUE TITLE
Document alerting on missing metrics under README.md/#Internal Monitoring

### ISSUE THREAD

**Issue by yanske1** [google/ts-bridge#30]
May be useful to document how someone can create alerts on missing timeseries in Service -> Alerts

cc @Dnefedkin

**Comment by knyar** [comment]
Do you think instructions and alert configuration in the [examples directory](https://github.com/google/ts-bridge/blob/master/examples/) is not sufficient?

**Comment by yanske1** [comment]
Whoops I missed that when I was looking for docs on it -- should be sufficient, I'll leave it up to Dima to decide. :)

**Comment by Dnefedkin** [comment]
Instructions in the examples directory are sufficient, so closing this one.
